/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/Index" |
       "/pages/mine/Index" |
       "/pages/components/icon/icon" |
       "/pages/components/list/list" |
       "/pages/components/upload/upload" |
       "/pages/components/form/form" |
       "/pages/components/button/button" |
       "/pages/components/cell/cell" |
       "/pages/components/badge/badge" |
       "/pages/components/tag/tag" |
       "/pages/components/swiper/swiper" |
       "/pages/components/picker/picker" |
       "/pages/components/datetimePicker/datetimePicker" |
       "/pages/components/addressPicker/addressPicker" |
       "/pages/components/search/search" |
       "/pages/components/rate/rate" |
       "/pages/components/numberBox/numberBox" |
       "/pages/components/input/input" |
       "/pages/components/textarea/textarea" |
       "/pages/components/checkButton/checkButton" |
       "/pages/components/checkbox/checkbox" |
       "/pages/components/radio/radio" |
       "/pages/components/slider/slider" |
       "/pages/components/switch/switch" |
       "/pages/components/lineProgress/lineProgress" |
       "/pages/components/scrollList/scrollList" |
       "/pages/components/line/line" |
       "/pages/components/card/card" |
       "/pages/components/overlay/overlay" |
       "/pages/components/grid/grid" |
       "/pages/components/divider/divider" |
       "/pages/components/tooltip/tooltip" |
       "/pages/components/warn/warn" |
       "/pages/components/noticeBar/noticeBar" |
       "/pages/components/foldingPanel/foldingPanel" |
       "/pages/components/popup/popup" |
       "/pages/components/modal/modal" |
       "/pages/components/readMore/readMore" |
       "/pages/components/navbar/navbar" |
       "/pages/components/backTop/backTop" |
       "/pages/components/tabs/tabs" |
       "/pages/components/subsection/subsection" |
       "/pages/components/steps/steps" |
       "/pages/components/empty/empty" |
       "/pages/components/avatar/avatar" |
       "/pages/components/transition/transition" |
       "/pages/components/qrcode/qrcode" |
       "/pages/components/loading/loading" |
       "/pages/components/calendar/calendar" |
       "/pages/components/swipeAction/swipeAction" |
       "/pages/components/image/image" |
       "/pages/components/countDown/countDown" |
       "/pages/components/countTo/countTo" |
       "/pages/components/floatButton/floatButton" |
       "/pages/components/dropdown/dropdown" |
       "/pages/components/text/text" |
       "/pages/components/parse/parse" |
       "/pages/components/submitBar/submitBar" |
       "/pages/components/price/price" |
       "/pages/components/login/login" |
       "/pages/components/waterfall/waterfall" |
       "/pages/components/toast/toast" |
       "/pages/components/configProvider/configProvider" |
       "/pages/components/codeInput/codeInput" |
       "/pages/components/notify/notify" |
       "/pages/components/signature/signature" |
       "/pages/components/pagination/pagination" |
       "/pages/components/menu/menu" |
       "/pages/components/watermark/watermark" |
       "/pages/components/tabBar/tabBar";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/Index" | "/pages/mine/Index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
